backend:
  name: github
  repo: dtinth/dt.in.th
publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "stuff"
    label: "Stuff"
    folder: "src/stuff"
    create: true
    slug: "{{id}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "stuff"}
      - {label: "ID", name: "id", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Created", name: "created", widget: "datetime"}
      - {label: "Updated", name: "updated", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean", required: false, default: false}
      - {label: "Featured Image", name: "featuredimage", widget: image, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
