backend:
  name: github
  repo: dtinth/dt.in.th
  # branch: netlify-cms
publish_mode: editorial_workflow
media_folder: 'static/uploads'
public_folder: '/uploads'
collections:
  - name: 'stuff'
    label: 'Stuff'
    folder: 'src/stuff'
    create: true
    slug: '{{id}}'
    fields:
      - { label: 'ID', name: 'id', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Created', name: 'created', widget: 'datetime' }
      - { label: 'Updated', name: 'updated', widget: 'datetime' }
      - {
          label: 'Description',
          name: 'description',
          widget: 'text',
          required: false,
        }
      - {
          label: 'Featured',
          name: 'featured',
          widget: 'boolean',
          required: false,
          default: false,
        }
      - { label: 'Image', name: 'image', widget: image, required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list', required: false }
