on:
  push:
    branches:
      - todo
name: Process TODO comments
jobs:
  collectTODO:
    name: Collect TODO
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set GitHub auth
      run: |
        git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
    - name: Collect TODO
      uses: dtinth/todo-actions@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TODO_ACTIONS_MONGO_URL: ${{ secrets.TODO_ACTIONS_MONGO_URL }}